from typing import Dict, Any, List

NUMERIC_SENSORS: List[Dict[str, Any]] = [
    {
        "name": "Solar Power",
        "key": "power_active",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power",
        "enabled": True,
    },
    {
        "name": "Input Power",
        "key": "power_input",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-panel",
        "enabled": True,
    },
    {
        "name": "Grid Power",
        "key": "meter_power_active",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "enabled": True,
    },
    {
        "name": "Battery Power",
        "key": "battery_power",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
        "enabled": True,
    },

    {
        "name": "Solar Daily Yield",
        "key": "energy_yield_day",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
        "enabled": True,
    },
    {
        "name": "Solar Total Yield",
        "key": "energy_yield_accumulated",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
        "enabled": True,
    },
    {
        "name": "Grid Energy Exported",
        "key": "energy_grid_exported",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-export",
        "enabled": True,
    },
    {
        "name": "Grid Energy Imported",
        "key": "energy_grid_accumulated",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-import",
        "enabled": True,
    },

    {
        "name": "Battery SOC",
        "key": "battery_soc",
        "unit_of_measurement": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "icon": "mdi:battery",
        "enabled": True,
    },
    {
        "name": "Battery Charge Today",
        "key": "battery_charge_day",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-plus",
        "enabled": True,
    },
    {
        "name": "Battery Discharge Today",
        "key": "battery_discharge_day",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-minus",
        "enabled": True,
    },
    {
        "name": "Battery Total Charge",
        "key": "battery_charge_total",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "enabled": True,
    },
    {
        "name": "Battery Total Discharge",
        "key": "battery_discharge_total",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "enabled": True,
    },
    {
        "name": "Battery Bus Voltage",
        "key": "battery_bus_voltage",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Battery Bus Current",
        "key": "battery_bus_current",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "enabled": True,
    },

    {
        "name": "PV1 Voltage",
        "key": "voltage_PV1",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "PV1 Current",
        "key": "current_PV1",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "enabled": True,
    },

    {
        "name": "PV2 Voltage",
        "key": "voltage_PV2",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": False,
    },
    {
        "name": "PV2 Current",
        "key": "current_PV2",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "enabled": False,
    },
    {
        "name": "PV3 Voltage",
        "key": "voltage_PV3",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": False,
    },
    {
        "name": "PV3 Current",
        "key": "current_PV3",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "enabled": False,
    },
    {
        "name": "PV4 Voltage",
        "key": "voltage_PV4",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": False,
    },
    {
        "name": "PV4 Current",
        "key": "current_PV4",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "enabled": False,
    },

    {
        "name": "Inverter Temperature",
        "key": "inverter_temperature",
        "unit_of_measurement": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Inverter Efficiency",
        "key": "inverter_efficiency",
        "unit_of_measurement": "%",
        "state_class": "measurement",
        "icon": "mdi:gauge",
        "enabled": True,
    },
    {
        "name": "Day Peak Power",
        "key": "power_active_peak_day",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Reactive Power",
        "key": "power_reactive",
        "unit_of_measurement": "var",
        "device_class": "reactive_power",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Power Factor",
        "key": "power_factor",
        "unit_of_measurement": "",
        "state_class": "measurement",
        "icon": "mdi:sine-wave",
        "enabled": True,
    },
    {
        "name": "Insulation Resistance",
        "key": "inverter_insulation_resistance",
        "unit_of_measurement": "MΩ",
        "state_class": "measurement",
        "icon": "mdi:lightning-bolt-circle",
        "enabled": True,
        "entity_category": "diagnostic",
    },

    {
        "name": "Grid Voltage Phase A",
        "key": "voltage_grid_A",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Grid Voltage Phase B",
        "key": "voltage_grid_B",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Grid Voltage Phase C",
        "key": "voltage_grid_C",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Line Voltage A-B",
        "key": "voltage_line_AB",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Line Voltage B-C",
        "key": "voltage_line_BC",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Line Voltage C-A",
        "key": "voltage_line_CA",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Grid Frequency",
        "key": "frequency_grid",
        "unit_of_measurement": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "enabled": True,
    },

    {
        "name": "Meter Reactive Power",
        "key": "meter_reactive_power",
        "unit_of_measurement": "var",
        "device_class": "reactive_power",
        "state_class": "measurement",
        "enabled": True,
    },

    {
        "name": "Meter Power Phase A",
        "key": "power_meter_A",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "enabled": True,
    },
    {
        "name": "Meter Power Phase B",
        "key": "power_meter_B",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "enabled": True,
    },
    {
        "name": "Meter Power Phase C",
        "key": "power_meter_C",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "enabled": True,
    },

    {
        "name": "Meter Line Voltage A-B",
        "key": "voltage_meter_line_AB",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Meter Line Voltage B-C",
        "key": "voltage_meter_line_BC",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Meter Line Voltage C-A",
        "key": "voltage_meter_line_CA",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "enabled": True,
    },

    {
        "name": "Meter Current Phase A",
        "key": "current_meter_A",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Meter Current Phase B",
        "key": "current_meter_B",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Meter Current Phase C",
        "key": "current_meter_C",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "enabled": True,
    },

    {
        "name": "Meter Frequency",
        "key": "frequency_meter",
        "unit_of_measurement": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "enabled": True,
    },
    {
        "name": "Meter Power Factor",
        "key": "power_factor_meter",
        "unit_of_measurement": "",
        "state_class": "measurement",
        "icon": "mdi:sine-wave",
        "enabled": True,
    },

    {
        "name": "Rated Power",
        "key": "rated_power",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:gauge",
        "enabled": True,
        "entity_category": "diagnostic",
    },
]

TEXT_SENSORS: List[Dict[str, Any]] = [
    {
        "name": "Inverter Status",
        "key": "inverter_status",
        "icon": "mdi:information",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Battery Status",
        "key": "battery_status",
        "icon": "mdi:battery-heart",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Meter Status",
        "key": "meter_status",
        "icon": "mdi:meter-electric",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Model Name",
        "key": "model_name",
        "icon": "mdi:information",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Serial Number",
        "key": "serial_number",
        "icon": "mdi:barcode",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Inverter State 1",
        "key": "inverter_state_1",
        "enabled": False,
        "entity_category": "diagnostic",
    },
    {
        "name": "Inverter State 2",
        "key": "inverter_state_2",
        "enabled": False,
        "entity_category": "diagnostic",
    },
    {
        "name": "Inverter Startup Time",
        "key": "startup_time",
        "device_class": "timestamp",
        "enabled": False,
        "entity_category": "diagnostic",
    },
]
